name: 'Build number service'
description:
  'Provides unique, always incrementing build numbers in a thread-safe manner'
author: 'Milestone Systems A/S'

# Define your inputs here.
inputs:
  build-identifier:
    description: 'The identifier for which the next build number is desired'
    required: true

# Define your outputs here.
outputs:
  build-identifier:
    description: 'The build identifier provided as input to the action'
  build-number:
    description:
      'The (next) unique build-number for the provided build identifier'

runs:
  using: node20
  main: dist/index.js
